function [softmax1000, state] = cum(sequence, params, varargin)
%CUM Function implementing an imported ONNX network.
%
% THIS FILE WAS AUTO-GENERATED BY importONNXFunction.
% ONNX Operator Set Version: 8
%
% Variable names in this function are taken from the original ONNX file.
%
% [SOFTMAX1000] = cum(SEQUENCE, PARAMS)
%			- Evaluates the imported ONNX network CUM with input(s)
%			SEQUENCE and the imported network parameters in PARAMS. Returns
%			network output(s) in SOFTMAX1000.
%
% [SOFTMAX1000, STATE] = cum(SEQUENCE, PARAMS)
%			- Additionally returns state variables in STATE. When training,
%			use this form and set TRAINING to true.
%
% [__] = cum(SEQUENCE, PARAMS, 'NAME1', VAL1, 'NAME2', VAL2, ...)
%			- Specifies additional name-value pairs described below:
%
% 'Training'
% 			Boolean indicating whether the network is being evaluated for
%			prediction or training. If TRAINING is true, state variables
%			will be updated.
%
% 'InputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			 between the dimensions of the input data and the dimensions of
%			the ONNX model input. For example, the permutation from HWCN
%			(MATLAB standard) to NCHW (ONNX standard) uses the vector
%			[4 3 1 2]. See the documentation for IMPORTONNXFUNCTION for
%			more information about automatic permutation.
%
%			'none' - Input(s) are passed in the ONNX model format. See 'Inputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between input data dimensions and the expected
%			ONNX input dimensions.%
%			cell array - If the network has multiple inputs, each cell
%			contains 'auto', 'none', or a numeric vector.
%
% 'OutputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			between the dimensions of the output and a conventional MATLAB
%			dimension ordering. For example, the permutation from NC (ONNX
%			standard) to CN (MATLAB standard) uses the vector [2 1]. See
%			the documentation for IMPORTONNXFUNCTION for more information
%			about automatic permutation.
%
%			'none' - Return output(s) as given by the ONNX model. See 'Outputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between the ONNX output dimensions and the
%			desired output dimensions.%
%			cell array - If the network has multiple outputs, each cell
%			contains 'auto', 'none' or a numeric vector.
%
% Inputs:
% -------
% SEQUENCE
%			- Input(s) to the ONNX network.
%			  The input size(s) expected by the ONNX file are:
%				  SEQUENCE:		[sequence_SequenceLength, BatchSize, 300, 1]				Type: FLOAT
%			  By default, the function will try to permute the input(s)
%			  into this dimension ordering. If the default is incorrect,
%			  use the 'InputDataPermutation' argument to control the
%			  permutation.
%
%
% PARAMS	- Network parameters returned by 'importONNXFunction'.
%
%
% Outputs:
% --------
% SOFTMAX1000
%			- Output(s) of the ONNX network.
%			  Without permutation, the size(s) of the outputs are:
%				  SOFTMAX1000:		[1, BatchSize, 2]				Type: FLOAT
%			  By default, the function will try to permute the output(s)
%			  from this dimension ordering into a conventional MATLAB
%			  ordering. If the default is incorrect, use the
%			  'OutputDataPermutation' argument to control the permutation.
%
% STATE		- (Optional) State variables. When TRAINING is true, these will
% 			  have been updated from the original values in PARAMS.State.
%
%
%  See also importONNXFunction

% Preprocess the input data and arguments:
[sequence, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(sequence, params, varargin{:});
% Put all variables into a single struct to implement dynamic scoping:
[Vars, NumDims] = packageVariables(params, {'sequence'}, {sequence}, [4]);
% Call the top-level graph function:
[softmax1000, softmax1000NumDims, state] = NetworkGraph1002(sequence, NumDims.sequence, Vars, NumDims, Training, params.State);
% Postprocess the output data
[softmax1000] = postprocessOutput(softmax1000, outputDataPerms, anyDlarrayInputs, Training, varargin{:});
end

function [softmax1000, softmax1000NumDims1025, state] = NetworkGraph1002(sequence, sequenceNumDims1024, Vars, NumDims, Training, state)
% Function implementing the graph 'NetworkGraph1002'
% Update Vars and NumDims from the graph's formal input parameters. Note that state variables are already in Vars.
Vars.sequence = sequence;
NumDims.sequence = sequenceNumDims1024;

% Execute the operators:
% Transpose:
[perm, NumDims.transpose1001] = prepareTransposeArgs(Vars.TransposePerm1003, NumDims.sequence);
if ~isempty(perm)
    Vars.transpose1001 = permute(Vars.sequence, perm);
end

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.conv1d_1] = prepareConvArgs(Vars.conv1d_1_W, Vars.conv1d_1_B, Vars.ConvStride1004, Vars.ConvDilationFactor1005, Vars.ConvPadding1006, 1, NumDims.transpose1001, NumDims.conv1d_1_W);
Vars.conv1d_1 = dlconv(Vars.transpose1001, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Transpose:
[perm, NumDims.transpose_1] = prepareTransposeArgs(Vars.TransposePerm1007, NumDims.conv1d_1);
if ~isempty(perm)
    Vars.transpose_1 = permute(Vars.conv1d_1, perm);
end

% Transpose:
[perm, NumDims.transpose_2] = prepareTransposeArgs(Vars.TransposePerm1008, NumDims.transpose_1);
if ~isempty(perm)
    Vars.transpose_2 = permute(Vars.transpose_1, perm);
end

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.maxpool1d_1] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1009, Vars.MaxPoolStride1010, Vars.MaxPoolPadding1011, NumDims.transpose_2);
Vars.maxpool1d_1 = maxpool(Vars.transpose_2, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Transpose:
[perm, NumDims.transpose_3] = prepareTransposeArgs(Vars.TransposePerm1012, NumDims.maxpool1d_1);
if ~isempty(perm)
    Vars.transpose_3 = permute(Vars.maxpool1d_1, perm);
end

% Relu:
Vars.relu_1 = relu(Vars.transpose_3);
NumDims.relu_1 = NumDims.transpose_3;

% Transpose:
[perm, NumDims.transpose_4] = prepareTransposeArgs(Vars.TransposePerm1013, NumDims.relu_1);
if ~isempty(perm)
    Vars.transpose_4 = permute(Vars.relu_1, perm);
end

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.conv1d_2] = prepareConvArgs(Vars.conv1d_2_W, Vars.conv1d_2_B, Vars.ConvStride1014, Vars.ConvDilationFactor1015, Vars.ConvPadding1016, 1, NumDims.transpose_4, NumDims.conv1d_2_W);
Vars.conv1d_2 = dlconv(Vars.transpose_4, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Transpose:
[perm, NumDims.transpose_5] = prepareTransposeArgs(Vars.TransposePerm1017, NumDims.conv1d_2);
if ~isempty(perm)
    Vars.transpose_5 = permute(Vars.conv1d_2, perm);
end

% Transpose:
[perm, NumDims.transpose_6] = prepareTransposeArgs(Vars.TransposePerm1018, NumDims.transpose_5);
if ~isempty(perm)
    Vars.transpose_6 = permute(Vars.transpose_5, perm);
end

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.maxpool1d_2] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1019, Vars.MaxPoolStride1020, Vars.MaxPoolPadding1021, NumDims.transpose_6);
Vars.maxpool1d_2 = maxpool(Vars.transpose_6, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Transpose:
[perm, NumDims.transpose_7] = prepareTransposeArgs(Vars.TransposePerm1022, NumDims.maxpool1d_2);
if ~isempty(perm)
    Vars.transpose_7 = permute(Vars.maxpool1d_2, perm);
end

% Relu:
Vars.relu_2 = relu(Vars.transpose_7);
NumDims.relu_2 = NumDims.transpose_7;

% Transpose:
[perm, NumDims.flatten_Transpose] = prepareTransposeArgs(Vars.TransposePerm1023, NumDims.relu_2);
if ~isempty(perm)
    Vars.flatten_Transpose = permute(Vars.relu_2, perm);
end

% Reshape:
[shape, NumDims.flatten_Reshape] = prepareReshapeArgs(Vars.flatten_Transpose, Vars.flatten_Reshape_shape, NumDims.flatten_Transpose);
Vars.flatten_Reshape = reshape(Vars.flatten_Transpose, shape{:});

% MatMul:
[Vars.fc_1_MatMul, NumDims.fc_1_MatMul] = onnxMatMul(Vars.flatten_Reshape, Vars.fc_1_MatMul_W, NumDims.flatten_Reshape, NumDims.fc_1_MatMul_W);

% Add:
Vars.fc_1_Add = Vars.fc_1_MatMul + Vars.fc_1_Add_B;
NumDims.fc_1_Add = max(NumDims.fc_1_MatMul, NumDims.fc_1_Add_B);

% Relu:
Vars.relu_3 = relu(Vars.fc_1_Add);
NumDims.relu_3 = NumDims.fc_1_Add;

% MatMul:
[Vars.fc_2_MatMul, NumDims.fc_2_MatMul] = onnxMatMul(Vars.relu_3, Vars.fc_2_MatMul_W, NumDims.relu_3, NumDims.fc_2_MatMul_W);

% Add:
Vars.fc_2_Add = Vars.fc_2_MatMul + Vars.fc_2_Add_B;
NumDims.fc_2_Add = max(NumDims.fc_2_MatMul, NumDims.fc_2_Add_B);

% Softmax:
[dim1, dim2, origSize, NumDims.softmax1000] = prepareSoftmaxArgs(Vars.fc_2_Add, 2, NumDims.fc_2_Add);
Vars.softmax1000 = reshape(Vars.fc_2_Add, dim1, dim2);
Vars.softmax1000 = softmax(Vars.softmax1000, 'DataFormat', 'CB');
Vars.softmax1000 = reshape(Vars.softmax1000, origSize);

% Set graph output arguments from Vars and NumDims:
softmax1000 = Vars.softmax1000;
softmax1000NumDims1025 = NumDims.softmax1000;
% Set output state from Vars:
state = updateStruct(state, Vars);
end

function [inputDataPerms, outputDataPerms, Training] = parseInputs(sequence, numDataOutputs, params, varargin)
% Function to validate inputs to cum:
p = inputParser;
isValidArrayInput = @(x)isnumeric(x) || isstring(x);
isValidONNXParameters = @(x)isa(x, 'ONNXParameters');
addRequired(p, 'sequence', isValidArrayInput);
addRequired(p, 'params', isValidONNXParameters);
addParameter(p, 'InputDataPermutation', 'auto');
addParameter(p, 'OutputDataPermutation', 'auto');
addParameter(p, 'Training', false);
parse(p, sequence, params, varargin{:});
inputDataPerms = p.Results.InputDataPermutation;
outputDataPerms = p.Results.OutputDataPermutation;
Training = p.Results.Training;
if isnumeric(inputDataPerms)
    inputDataPerms = {inputDataPerms};
end
if isstring(inputDataPerms) && isscalar(inputDataPerms) || ischar(inputDataPerms)
    inputDataPerms = repmat({inputDataPerms},1,1);
end
if isnumeric(outputDataPerms)
    outputDataPerms = {outputDataPerms};
end
if isstring(outputDataPerms) && isscalar(outputDataPerms) || ischar(outputDataPerms)
    outputDataPerms = repmat({outputDataPerms},1,numDataOutputs);
end
end

function [sequence, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(sequence, params, varargin)
% Parse input arguments
[inputDataPerms, outputDataPerms, Training] = parseInputs(sequence, 1, params, varargin{:});
anyDlarrayInputs = any(cellfun(@(x)isa(x, 'dlarray'), {sequence}));
% Make the input variables into unlabelled dlarrays:
sequence = makeUnlabeledDlarray(sequence);
% Permute inputs if requested:
sequence = permuteInputVar(sequence, inputDataPerms{1}, 4);
% Check input size(s):
checkInputSize(size(sequence), {'sequence_SequenceLength' 'BatchSize' 300 1}, "sequence");
end

function [softmax1000] = postprocessOutput(softmax1000, outputDataPerms, anyDlarrayInputs, Training, varargin)
% Set output type:
if ~anyDlarrayInputs && ~Training
    if isdlarray(softmax1000)
        softmax1000 = extractdata(softmax1000);
    end
end
% Permute outputs if requested:
softmax1000 = permuteOutputVar(softmax1000, outputDataPerms{1}, 3);
end


%% dlarray functions implementing ONNX operators:

function [D, numDimsD] = onnxMatMul(A, B, numDimsA, numDimsB)
% Implements the ONNX MatMul operator.

% If either arg is more than 2D, loop over all dimensions before the final
% 2. Inside the loop, perform matrix multiplication.

% If B is 1-D, temporarily extend it to a row vector
if numDimsB==1
    B = B(:)';
end
maxNumDims = max(numDimsA, numDimsB);
numDimsD = maxNumDims;
if maxNumDims > 2
    % sizes of matrices to be multiplied
    matSizeA        = size(A, 1:2);
    matSizeB        = size(B, 1:2);
    % size of the stack of matrices
    stackSizeA      = size(A, 3:maxNumDims);
    stackSizeB      = size(B, 3:maxNumDims);
    % final stack size
    resultStackSize = max(stackSizeA, stackSizeB);
    % full implicitly-expanded sizes
    fullSizeA       = [matSizeA resultStackSize];
    fullSizeB       = [matSizeB resultStackSize];
    resultSize      = [matSizeB(1) matSizeA(2) resultStackSize];
    % Repmat A and B up to the full stack size using implicit expansion
    A = A + zeros(fullSizeA);
    B = B + zeros(fullSizeB);
    % Reshape A and B to flatten the stack dims (all dims after the first 2)
    A2 = reshape(A, size(A,1), size(A,2), []);
    B2 = reshape(B, size(B,1), size(B,2), []);
    % Iterate down the stack dim, doing the 2d matrix multiplications
    D2 = zeros([matSizeB(1), matSizeA(2), size(A2,3)], 'like', A);
    for i = size(A2,3):-1:1
        D2(:,:,i) = B2(:,:,i) * A2(:,:,i);
    end
    % Reshape D2 to the result size (unflatten the stack dims)
    D = reshape(D2, resultSize);
else
    D = B * A;
    if numDimsA==1 || numDimsB==1
        D = D(:);
        numDimsD = 1;
    end
end
end

function [weights, bias, stride, dilationFactor, padding, dataFormat, numDimsY] = prepareConvArgs(...
    weights, bias, stride, dilationFactor, padding, numWtGroups, numDimsX, numDimsW)
% Prepares arguments for implementing the ONNX Conv operator

% Weights: The ONNX weight dim is Fcxyz..., where c=C/G, G is numGroups,
% and xyz... are spatial dimensions. DLT "weights" here is the flip of
% that, or ...zyxcF. dlconv requires ...zyxcfG, where f=F/G. So reshape to
% split the last dimension.
sizeW    = size(weights, 1:numDimsW);
F        = sizeW(end);
newWSize = [sizeW(1:numDimsW-1), F/numWtGroups, numWtGroups];
weights  = reshape(weights, newWSize);
% bias
if isempty(bias)
    bias = 0;
end
bias = dlarray(bias(:),'CU');
% Derive missing default attributes from weight tensor
numSpatialDims = numDimsW-2;
if isempty(padding)
    padding = zeros(1, 2*numSpatialDims);
end
if isempty(stride)
    stride = ones(1,numSpatialDims);
end
if isempty(dilationFactor)
    dilationFactor = ones(1,numSpatialDims);
end
% Make the attributes non-dlarrays:
if isa(stride, 'dlarray')
    stride = extractdata(stride);
end
if isa(dilationFactor, 'dlarray')
    dilationFactor = extractdata(dilationFactor);
end
if isa(padding, 'dlarray')
    padding = extractdata(padding);
end
% Make the attributes double row vectors, and flip their dimension ordering
% to reverse-onnx:
stride = fliplr(double(stride(:)'));
dilationFactor = fliplr(double(dilationFactor(:)'));
if isnumeric(padding)       % padding can be "same"
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the lrflip and semicolon)
    padding = fliplr(transpose(reshape(padding, [], 2)));
end
% Set dataformat and numdims
dataFormat = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY = numDimsX;
end

function [poolsize, stride, padding, dataFormat, numDimsY, numDimsIndices] = prepareMaxPool8Args(poolsize, stride, padding, numDimsX)
% Prepares arguments for implementing the ONNX MaxPool-8 operator
poolsize    = fliplr(extractdata(poolsize(:)'));
stride      = fliplr(extractdata(stride(:)'));
% padding
if isa(padding, 'dlarray')
    padding = extractdata(padding);
end
if isnumeric(padding)
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the lrflip and semicolon)
    padding = fliplr(transpose(reshape(padding, [], 2)));
end
dataFormat  = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY    = numDimsX;
numDimsIndices = numDimsX;                      % New in opset 8
end

function [DLTShape, numDimsY] = prepareReshapeArgs(X, ONNXShape, numDimsX)
% Prepares arguments for implementing the ONNX Reshape operator
ONNXShape = flip(extractdata(ONNXShape));            % First flip the shape to make it correspond to the dimensions of X.
% In ONNX, 0 means "unchanged", and -1 means "infer". In DLT, there is no
% "unchanged", and [] means "infer".
DLTShape = num2cell(ONNXShape);                      % Make a cell array so we can include [].
% Replace zeros with the actual size
if any(ONNXShape==0)
    i0 = find(ONNXShape==0);
    DLTShape(i0) = num2cell(size(X, numDimsX - numel(ONNXShape) + i0));  % right-align the shape vector and dims
end
if any(ONNXShape == -1)
    % Replace -1 with []
    i = ONNXShape == -1;
    DLTShape{i} = [];
end
if numel(DLTShape)==1
    DLTShape = [DLTShape 1];
end
numDimsY = numel(ONNXShape);
end

function [dim1, dim2, origSize, numDimsX] = prepareSoftmaxArgs(X, ONNXAxis, numDimsX)
% Prepares arguments for implementing the ONNX Softmax operator
if ONNXAxis<0
    ONNXAxis = ONNXAxis + numDimsX;
end
dim2     = prod(size(X, numDimsX+1-ONNXAxis:numDimsX));   % numel on the right
dim1     = numel(X)/dim2;                                 % numel on the left
origSize = size(X);
end

function [perm, numDimsA] = prepareTransposeArgs(ONNXPerm, numDimsA)
% Prepares arguments for implementing the ONNX Transpose operator
if numDimsA <= 1        % Tensors of numDims 0 or 1 are unchanged by ONNX Transpose.
    perm = [];
else
    if isempty(ONNXPerm)        % Empty ONNXPerm means reverse the dimensions.
        perm = numDimsA:-1:1;
    else
        perm = numDimsA-flip(ONNXPerm);
    end
end
end

%% Utility functions:

function s = appendStructs(varargin)
% s = appendStructs(s1, s2,...). Assign all fields in s1, s2,... into s.
if isempty(varargin)
    s = struct;
else
    s = varargin{1};
    for i = 2:numel(varargin)
        fromstr = varargin{i};
        fs = fieldnames(fromstr);
        for j = 1:numel(fs)
            s.(fs{j}) = fromstr.(fs{j});
        end
    end
end
end

function checkInputSize(inputShape, expectedShape, inputName)

if numel(expectedShape)==0
    % The input is a scalar
    if ~isequal(inputShape, [1 1])
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, "[1,1]", inputSizeStr));
    end
elseif numel(expectedShape)==1
    % The input is a vector
    if ~shapeIsColumnVector(inputShape) || ~iSizesMatch({inputShape(1)}, expectedShape)
        expectedShape{2} = 1;
        expectedSizeStr = makeSizeString(expectedShape);
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
else
    % The input has 2 dimensions or more
    
    % The input dimensions have been reversed; flip them back to compare to the
    % expected ONNX shape.
    inputShape = fliplr(inputShape);
    
    % If the expected shape has fewer dims than the input shape, error.
    if numel(expectedShape) < numel(inputShape)
        expectedSizeStr = strjoin(["[", strjoin(string(expectedShape), ","), "]"], "");
        error(message('nnet_cnn_onnx:onnx:InputHasGreaterNDims', inputName, expectedSizeStr));
    end
    
    % Prepad the input shape with trailing ones up to the number of elements in
    % expectedShape
    inputShape = num2cell([ones(1, numel(expectedShape) - length(inputShape)) inputShape]);
    
    % Find the number of variable size dimensions in the expected shape
    numVariableInputs = sum(cellfun(@(x) isa(x, 'char') || isa(x, 'string'), expectedShape));
    
    % Find the number of input dimensions that are not in the expected shape
    % and cannot be represented by a variable dimension
    nonMatchingInputDims = setdiff(string(inputShape), string(expectedShape));
    numNonMatchingInputDims  = numel(nonMatchingInputDims) - numVariableInputs;
    
    expectedSizeStr = makeSizeString(expectedShape);
    inputSizeStr = makeSizeString(inputShape);
    if numNonMatchingInputDims == 0 && ~iSizesMatch(inputShape, expectedShape)
        % The actual and expected input dimensions match, but in
        % a different order. The input needs to be permuted.
        error(message('nnet_cnn_onnx:onnx:InputNeedsPermute',inputName, expectedSizeStr, inputSizeStr));
    elseif numNonMatchingInputDims > 0
        % The actual and expected input sizes do not match.
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
end
end

function doesMatch = iSizesMatch(inputShape, expectedShape)
% Check whether the input and expected shapes match, in order.
% Size elements match if (1) the elements are equal, or (2) the expected
% size element is a variable (represented by a character vector or string)
doesMatch = true;
for i=1:numel(inputShape)
    if ~(isequal(inputShape{i},expectedShape{i}) || ischar(expectedShape{i}) || isstring(expectedShape{i}))
        doesMatch = false;
        return
    end
end
end

function sizeStr = makeSizeString(shape)
sizeStr = strjoin(["[", strjoin(string(shape), ","), "]"], "");
end

function isVec = shapeIsColumnVector(shape)
if numel(shape) == 2 && shape(2) == 1
    isVec = true;
else
    isVec = false;
end
end
function X = makeUnlabeledDlarray(X)
% Make numeric X into an unlabelled dlarray
if isa(X, 'dlarray')
    X = stripdims(X);
elseif isnumeric(X)
    if isinteger(X)
        % Make ints double so they can combine with anything without
        % reducing precision
        X = double(X);
    end
    X = dlarray(X);
end
end

function [Vars, NumDims] = packageVariables(params, inputNames, inputValues, inputNumDims)
% inputNames, inputValues are cell arrays. inputRanks is a numeric vector.
Vars = appendStructs(params.Learnables, params.Nonlearnables, params.State);
NumDims = params.NumDimensions;
% Add graph inputs
for i = 1:numel(inputNames)
    Vars.(inputNames{i}) = inputValues{i};
    NumDims.(inputNames{i}) = inputNumDims(i);
end
end

function X = permuteInputVar(X, userDataPerm, onnxNDims)
% Returns reverse-ONNX ordering
if onnxNDims == 0
    return;
elseif onnxNDims == 1 && isvector(X)
    X = X(:);
    return;
elseif isnumeric(userDataPerm)
    % Permute into reverse ONNX ordering
    if numel(userDataPerm) ~= onnxNDims
        error(message('nnet_cnn_onnx:onnx:InputPermutationSize', numel(userDataPerm), onnxNDims));
    end
    perm = fliplr(userDataPerm);
elseif isequal(userDataPerm, 'auto') && onnxNDims == 4
    % Permute MATLAB HWCN to reverse onnx (WHCN)
    perm = [2 1 3 4];
elseif isequal(userDataPerm, 'as-is')
    % Do not permute the input
    perm = 1:ndims(X);
else
    % userDataPerm is either 'none' or 'auto' with no default, which means
    % it's already in onnx ordering, so just make it reverse onnx
    perm = max(2,onnxNDims):-1:1;
end
X = permute(X, perm);
end

function Y = permuteOutputVar(Y, userDataPerm, onnxNDims)
switch onnxNDims
    case 0
        perm = [];
    case 1
        if isnumeric(userDataPerm)
            % Use the user's permutation because Y is a column vector which
            % already matches ONNX.
            perm = userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            % Treat the 1D onnx vector as a 2D column and transpose it
            perm = [2 1];
        else
            % userDataPerm is 'none'. Leave Y alone because it already
            % matches onnx.
            perm = [];
        end
    otherwise
        % ndims >= 2
        if isnumeric(userDataPerm)
            % Use the inverse of the user's permutation. This is not just the
            % flip of the permutation vector.
            perm = onnxNDims + 1 - userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            if onnxNDims == 2
                % Permute reverse ONNX CN to DLT CN (do nothing)
                perm = [];
            elseif onnxNDims == 4
                % Permute reverse onnx (WHCN) to MATLAB HWCN
                perm = [2 1 3 4];
            else
                % User wants the output in ONNX ordering, so just reverse it from
                % reverse onnx
                perm = onnxNDims:-1:1;
            end
        elseif isequal(userDataPerm, 'as-is')
            % Do not permute the input
            perm = 1:ndims(Y);
        else
            % userDataPerm is 'none', so just make it reverse onnx
            perm = onnxNDims:-1:1;
        end
end
if ~isempty(perm)
    Y = permute(Y, perm);
end
end

function s = updateStruct(s, t)
% Set all existing fields in s from fields in t, ignoring extra fields in t.
for name = transpose(fieldnames(s))
    s.(name{1}) = t.(name{1});
end
end
